name: 03_Input_Action
description: 'Demonstration of a composite action with an input parameter'

inputs:
  INPUT_TEXT_1:
    description: 'Value to print'
    required: false
    default: 'Hello from Input Action 03'

runs:
  using: "composite"
  steps:
    - name: Print Message Step 1
      run: echo "say => ${{ inputs.INPUT_TEXT_1 }}!"