name: Print_Messages
run-name:  Print Hello-World Flow
description: "This workflow prints a message inside a group in the GitHub Actions log."

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  print_message_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message Step 1
        run: echo "Hello world!"
        
      - name: Print Message Step 2
        run: echo "Great Job!"
  
  print_message_group_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Grouped Step 1
        run: |
          echo "::group::My title Group"
          echo "Inside group, message 1"
          echo "Inside group, message 2"
          echo "Inside group, message 3"
          echo "::endgroup::"
