name: 01_Print_Hello_World_Flow
run-name:  Print Hello-World Flow
description: "A simple workflow to print Hello World"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  print_hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World Step 1
        run: echo "Hello world!"
      - name: Print Hello World Step 2
        run: echo "Great Job!"
