name: Variables_Local
description: "This workflow demonstrates the use of environment variables, job-specific variables, and step-specific variables in GitHub Actions."

on:
  workflow_dispatch:

env:
  MY_GLOBAL_VARIABLE: "Any Global Value" # This variable is available to all jobs

jobs:
  list_variable_job:
    runs-on: ubuntu-latest
    env:
      MY_LOCAL_VARIABLE: "Hello, World!" # This variable is only available in this job
    steps:
      - name: Print Variables Step 1
        env:
          MY_STEP_VARIABLE: "For this step." # That are only available within a single step
        run: |
          echo "The value of MY_GLOBAL_VARIABLE is => ${{env.MY_GLOBAL_VARIABLE}}"
          echo "The value of MY_LOCAL_VARIABLE is => ${{env.MY_LOCAL_VARIABLE}}"
          echo "The value of MY_STEP_VARIABLE is => ${{env.MY_STEP_VARIABLE}}"
          echo "The value of MY_ENV_VARIABLE is => ${{vars.MY_TOKEN_VARIABLE}}"
          echo "The value of SECRET is => ${{secrets.MY_TOKEN_SECRET}}"
