name: Variables_Context
description: "This workflow lists various context variables available in GitHub Actions."

on:
  workflow_dispatch:

jobs:
  list_context_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print context Step 1
        run: |
          echo "The event that triggered this workflow is => ${{ github.event_name }}."
          echo "The repository name is => ${{ github.repository }}."
          echo "The actor who triggered this workflow is => ${{ github.actor }}."
      
      - name: Print context Step 2
        run: echo "The workflow job status is => ${{ job.status }}."

      - name: Print context Step 3
        run: echo "The runner's information is => ${{ runner.os }}."