name: List_Variable_Flow
on:
  workflow_dispatch:
env:
  MY_GLOBAL_VARIABLE: "Any Global Value" # This variable is available to all jobs
jobs:
  list_variable_job:
    runs-on: ubuntu-latest
    env:
      MY_LOCAL_VARIABLE: "Hello, World!" # This variable is only available in this job
    steps:
      - name: Print Variable Sep 4
        run: |
          echo "The value of MY_GLOBAL_VARIABLE is ${{env.MY_GLOBAL_VARIABLE}}"
          echo "The value of MY_LOCAL_VARIABLE is ${{env.MY_LOCAL_VARIABLE}}"
          echo "The value of MY_ENV_VARIABLE is ${{vars.MY_TOKEN_VARIABLE}}"
          echo "The value of SECRET is ${{secrets.MY_TOKEN_SECRET}}"
