name: Print_Hello_World
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
    inputs:
      example_input:
        description: "An example input for the workflow"
        required: false
        default: "default_value"
jobs:
  print_hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World Sep 1
        run: echo "Hello world!"
      - name: Print Hello World Sep 2
        run: echo "Great Job!"
