name: Print_Hello_World
on: 
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input for the workflow'
        required: false
        default: 'default_value'
jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - name: Print Hello World
        run: echo "Hello world!"