name: Print_Scheduled_Message
on:
  schedule:
    - cron: '*/2 * * * *' # This cron expression runs the workflow every 2 minutes
jobs:
  print_scheduled_message_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Scheduled Message Sep 1
        run: echo "This message is printed every 2 minutes."