name: 08_Use_Reusable_Work_Flow
description: 'Demonstration of using a reusable workflow'

on:
  workflow_dispatch:
    
jobs:
  use_reusable_workflow_job:
      uses: ./.github/workflows/sample-8_1.yaml