name: Using_Needs_Flow
on: 
  workflow_dispatch:
jobs:
  create_needed_job:
    runs-on: ubuntu-latest
    outputs:
      data_output_1: "Data from first job."
    steps:
      - name: Set Job Output Step 1
        run: echo "First job completed."
  use_needed_job:
    needs: create_needed_job
    runs-on: ubuntu-latest
    steps:
      - name: Use Output From First Job Step 1
        run: echo "Received from From First Job ${{ needs.create_needed_job.outputs.data_output_1 }}"
