name: 01_1_Print_Message_Flow

on:
  workflow_dispatch:

jobs:
  print_message_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Group Lines Step 1
        run: |
            echo "::group::My title Group"
            echo "Inside group, message 1"
            echo "Inside group, message 2"
            echo "Inside group, message 3"
            echo "::endgroup::"