name: 02_Print_Scheduled_Message_Flow
description: "This workflow prints a message every 5 minutes using a cron schedule. E.G.: schedule trigger only branch main"

on:
  workflow_dispatch: 
  schedule: # This cron expression runs the workflow every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  print_scheduled_message_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Scheduled Message Step 1
        run: echo "This message is printed every 5 minutes."
